# Generated by Django 2.0.3 on 2018-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
