# Generated by Django 2.0.3 on 2018-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20180412_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='poster_path',
            field=models.CharField(default='unspecified', max_length=500),
        ),
        migrations.AlterField(
            model_name='fake',
            name='actual_id',
            field=models.IntegerField(default=6049),
        ),
        migrations.AlterField(
            model_name='fake',
            name='fake_id',
            field=models.AutoField(default=945, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=945),
        ),
    ]
