# Generated by Django 2.2.2 on 2019-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20180418_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake',
            name='actual_id',
            field=models.IntegerField(default=6059),
        ),
        migrations.AlterField(
            model_name='fake',
            name='fake_id',
            field=models.AutoField(default=953, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=953),
        ),
    ]
