# Generated by Django 2.2.2 on 2019-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20190613_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake',
            name='actual_id',
            field=models.IntegerField(default=6060),
        ),
        migrations.AlterField(
            model_name='fake',
            name='fake_id',
            field=models.AutoField(default=954, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=954),
        ),
    ]
